---
- name: Ping all Linux servers
  hosts: linux
  tasks:
    - name: Ping servers
      ping:

- name: Ping Ubuntu servers
  hosts: linux1
  tasks:
    - name: Ping Ubuntu
      ping:

- name: Ping RedHat servers
  hosts: linux2
  tasks:
    - name: Ping RedHat
      ping:
