name: SEC460 DevSecOps Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  trivy-scan:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@57a97c7
        with:
          scan-type: fs
          scan-ref: .
          format: table
          exit-code: 1
          ignore-unfixed: true
          severity: CRITICAL,HIGH
